WebApplication1/Areas/Admin/Controllers/SliderController.cs
using WebApplication1.Areas.Admin.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    public class SliderController : Controller
    {
        bilgiBilgiSayEntities db = new bilgiBilgiSayEntities();
        //
        // GET: /Admin/Slider/
        public ActionResult Index()
        {
            var model = db.Slider.OrderByDescending(x => x.ID).ToList();
            return View(model);
        }
        public ActionResult Add()
        {
            return View();
        }
        const string imageFolderPath = "/content/slider-images/";
        public ActionResult AddSlider(SliderModel model)
        {
            if (ModelState.IsValid)
            {
                Slider slider = new Slider();
                string fileName = string.Empty;
                //SliderFoto Kayıt
                if (model.Resim != null && model.Resim.ContentLength > 0)
                {
                    fileName = model.Resim.FileName;
                    var path = Path.Combine(Server.MapPath("~" + imageFolderPath), fileName);
                    model.Resim.SaveAs(path);
                }



                
                slider.BaslangicTarih = model.BaslangicTarih;
                slider.BitisTarih = model.BitisTarih;
                slider.ResimYolu = imageFolderPath + fileName;

                db.Slider.Add(slider);
                db.SaveChanges();

            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Slider model)
        {
            if (ModelState.IsValid)
            {
                db.Slider.Attach(model);
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            else
            {
                return View(model);
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.Slider.Find(id);
            return View(model);
        }
        [HttpGet]
        public ActionResult DeleteConfirm(int id)
        {
            var model = db.Slider.Find(id);
            db.Slider.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

WebApplication1/Areas/Admin/Views/Slider/Add.cshtml
@model WebApplication1.Areas.Admin.Models.SliderModel

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div id="page-heading">
    <ol class="breadcrumb">
        <li><a href="index.htm">Dashboard</a></li>
        <li>UI Elements</li>
        <li class="active">Tables</li>
    </ol>

    <h1>Yeni Slider Ekle</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
<div class="container">
        <div class="row">
				<div class="col-sm-12">
				  <div class="panel panel-primary">
              <div class="panel-heading">
                  <h4>Form Layout</h4>
              </div>
                      @using (Html.BeginForm("AddSlider", "Slider", FormMethod.Post, new { @class = "form-horizontal", enctype="multipart/form-data"}))
                      {
                        <div class="panel-body">
                          <h3>Slide Ekle</h3>
                          <br>
                          <div class="form-group">
                              @Html.LabelFor(m=>m.BaslangicTarih, new {@class ="col-sm-3 control-label" })
                              <div class="col-sm-3">
                                  @Html.TextBoxFor(m => m.BaslangicTarih, new { @class = "form-control ",placeholder = "Baslangıç Tarihi (AA/GG/YY)" })
                              </div>             
                              <div class="col-sm-3">
                                  <p class="help-block">Your help text!</p>
                              </div>
                          </div>
                          <div class="form-group">
                              @Html.LabelFor(m => m.BitisTarih, new { @class = "col-sm-3 control-label" })
                              <div class="col-sm-3">
                                  @Html.TextBoxFor(m => m.BitisTarih, new { @class = "form-control", placeholder = "Bitiş Tarihi (AA/GG/YY)" })
                              </div>
                              <div class="col-sm-3">
                                  <p class="help-block">Your help text!</p>
                              </div>
                          </div>
                          <div class="form-group">
                            @Html.LabelFor(m => m.Resim, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-3">
                                @Html.TextBoxFor(m => m.Resim, new { @class = "form-control", placeholder = "Resim Yolu", type = "file" })
                            </div>
                            <div class="col-sm-3">
                                <p class="help-block">Your help text!</p>
                            </div>
                          </div>
                        </div>
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-6 col-sm-offset-3">
                                    <div class="btn-toolbar">
                                        <button class="btn-primary btn">Submit</button>
                                        <button class="btn-default btn">Cancel</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                      }
				      
				  </div>
				</div>
			</div>


    
</div>
@section pluginscss
    {

    <link rel='stylesheet' type='text/css' href='assets/plugins/jqueryui-timepicker/jquery.ui.timepicker.css' />
}
@section jsplugins
{
    @*<script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/fullcalendar/fullcalendar.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-daterangepicker/daterangepicker.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-daterangepicker/moment.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/charts-flot/jquery.flot.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/charts-flot/jquery.flot.resize.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/charts-flot/jquery.flot.orderBars.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/pulsate/jQuery.pulsate.min.js'></script>*@
    <script type='text/javascript' src='~/assets/plugins/codeprettifier/prettify.js'></script>
    <script type='text/javascript' src='~/assets/plugins/easypiechart/jquery.easypiechart.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/sparklines/jquery.sparklines.min.js'></script>
    <script type='text/javascript' src='~/assets/plugins/form-toggle/toggle.min.js'></script> 
}
@section scripts
    {
    <script type="text/javascript">
        $(".datepicker").datepicker({
            format: 'mm.dd.yyyy'
        });

    </script>
    }

WebApplication1/Areas/Admin/Views/Slider/Delete.cshtml
@model WebApplication1.Slider

@{
    ViewBag.Title = "Slider Fotoğrafı Sil";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>@Model.ID id'li fotoğrafı sil</h2>
<p>Silmek istediğinize emin misiniz ? </p>
<br />
@Html.ActionLink("Sil","DeleteConfirm")
<br />
@Html.ActionLink("Vazgeç", "Index")

WebApplication1/Areas/Admin/Views/Slider/Edit.cshtml
@model WebApplication1.Slider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        @*<div class="form-group">
                @Html.LabelFor(model => model.SliderFoto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SliderFoto, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SliderFoto, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.BaslangicTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BaslangicTarih, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.BaslangicTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BitisTarih, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BitisTarih, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.BitisTarih, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYolu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYolu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYolu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApplication1/Areas/Admin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div id="page-heading">

    <h1>Slidelar</h1>
    <div class="options">
        <div class="btn-toolbar">
            <div class="btn-group hidden-xs">
                <a href='#' class="btn btn-default dropdown-toggle" data-toggle='dropdown'><i class="fa fa-cloud-download"></i><span class="hidden-sm"> Export as  </span><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Text File (*.txt)</a></li>
                    <li><a href="#">Excel File (*.xlsx)</a></li>
                    <li><a href="#">PDF File (*.pdf)</a></li>
                </ul>
            </div>
            <a href="#" class="btn btn-default"><i class="fa fa-cog"></i></a>
        </div>
    </div>
</div>
@Html.ActionLink("Yeni Slide Ekle", "Add")
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4>Slider Tablosu</h4>
                    <div class="options">

                    </div>
                </div>
                <div class="panel-body">
                    
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>
                                <th>Resim Yolu</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {   
                                <tr>
                                    <td>@item.ID</td>
                                    <td>@item.BaslangicTarih</td>
                                    <td>@item.BitisTarih</td>
                                    <td>@item.ResimYolu</td>
                                    <td>@Html.ActionLink("Düzenle", "Edit", "Slider", new { id = item.ID }, null) | @Html.ActionLink("Sil", "Delete", "Slider", new { id = item.ID }, null) </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>